In [516]:
import time

import numpy as np
lenth = 1500000
s = np.mat(np.random.binomial(1, 0.6, lenth))
print(s.sum()/lenth)
print(s)

s_ori = np.copy(s)

change1_to_0 = (1 - np.random.binomial(1, 0.3, lenth))
s = np.multiply(s, change1_to_0)
print(s.sum()/lenth)
check = np.multiply((1 - s), (1 - s_ori))
print(np.all((1 - s_ori) == check))

def f_1_to_0(sin, change1_to_0):
    change1_to_0 = 1- change1_to_0
    return np.multiply(sin, change1_to_0)

change0_to_1 = np.random.binomial(1, 0.5, lenth)
print(change0_to_1.sum() / lenth)
print('', change0_to_1)
s = 1 - f_1_to_0(1-s, change0_to_1)
print(s.sum()/lenth)
print(s)

0.5996553333333333
[[0 1 0 ... 0 1 1]]
0.419672
True


In [309]:
s = np.mat([0,0,1,1])
change0_to_1 = np.array([1, 0, 1, 0])
s = 1 - s
s = np.multiply(s, change0_to_1)
s = 1 - s
print(s)

[[0 1 1 1]]


In [558]:
popu = np.mat(np.random.binomial(1, 0.5, 100), 'int8')
print(popu)

[[0 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 0 0 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0
  0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1
  0 1 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0]]


In [597]:
sl_n = 10
ind_n = 5
popu_slots = np.array(np.zeros([sl_n, ind_n, 12], 'int8'))
for i in range(0, sl_n):
    for j in range(0, ind_n):
        popu_slots[i, j, 0] = i*ind_n + j
print(popu_slots)

[[[ 0  0  0  0  0  0  0  0  0  0  0  0]
  [ 1  0  0  0  0  0  0  0  0  0  0  0]
  [ 2  0  0  0  0  0  0  0  0  0  0  0]
  [ 3  0  0  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 5  0  0  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0  0  0]
  [ 7  0  0  0  0  0  0  0  0  0  0  0]
  [ 8  0  0  0  0  0  0  0  0  0  0  0]
  [ 9  0  0  0  0  0  0  0  0  0  0  0]]

 [[10  0  0  0  0  0  0  0  0  0  0  0]
  [11  0  0  0  0  0  0  0  0  0  0  0]
  [12  0  0  0  0  0  0  0  0  0  0  0]
  [13  0  0  0  0  0  0  0  0  0  0  0]
  [14  0  0  0  0  0  0  0  0  0  0  0]]

 [[15  0  0  0  0  0  0  0  0  0  0  0]
  [16  0  0  0  0  0  0  0  0  0  0  0]
  [17  0  0  0  0  0  0  0  0  0  0  0]
  [18  0  0  0  0  0  0  0  0  0  0  0]
  [19  0  0  0  0  0  0  0  0  0  0  0]]

 [[20  0  0  0  0  0  0  0  0  0  0  0]
  [21  0  0  0  0  0  0  0  0  0  0  0]
  [22  0  0  0  0  0  0  0  0  0  0  0]
  [23  0  0  0  0  0  0  0  0  0  0  0]
  [24  0  0  0  0  0  0  0  0  0

In [631]:
ran_indic = 22
si = ran_indic // ind_n
ii = ran_indic % ind_n
indie = (si, ii)
x = popu_slots[indie]
x = x -100
print(popu_slots[indie])
print(x)

[22  0  0  0  0  0  0  0  0  0  0  0]
[ -78 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100]


In [589]:
t0 = time.time()
for i in range(0, 100_0000):
    sl_ind = i % sl_n
    indi_ind = i % ind_n
    choose = popu_slots[sl_ind, indi_ind, :]
    choose = choose + 1
    # popu_slots[sl_ind, indi_ind, :] = choose
print(time.time() - t0)


1.7598116397857666
