In [1]:
import time

import numpy as np
lenth = 1500000
s = np.mat(np.random.binomial(1, 0.6, lenth))
print(s.sum()/lenth)
print(s)

s_ori = np.copy(s)

change1_to_0 = (1 - np.random.binomial(1, 0.3, lenth))
s = np.multiply(s, change1_to_0)
print(s.sum()/lenth)
check = np.multiply((1 - s), (1 - s_ori))
print(np.all((1 - s_ori) == check))

def f_1_to_0(sin, change1_to_0):
    change1_to_0 = 1- change1_to_0
    return np.multiply(sin, change1_to_0)

change0_to_1 = np.random.binomial(1, 0.5, lenth)
print(change0_to_1.sum() / lenth)
print('', change0_to_1)
s = 1 - f_1_to_0(1-s, change0_to_1)
print(s.sum()/lenth)
print(s)

0.599782
[[1 1 1 ... 0 0 1]]
0.420078
True
0.499594
 [0 1 1 ... 0 0 0]
0.7097046666666667
[[0 1 1 ... 0 0 1]]


In [2]:
s = np.mat([0,0,1,1])
change0_to_1 = np.array([1, 0, 1, 0])
s = 1 - s
s = np.multiply(s, change0_to_1)
s = 1 - s
print(s)

[[0 1 1 1]]


In [ ]:
np.inf == np.inf

In [ ]:
popu = np.mat(np.random.binomial(1, 0.5, 100), 'int8')
print(popu)

In [ ]:
sl_n = 10
ind_n = 5
popu_slots = np.array(np.zeros([sl_n, ind_n, 12], 'int8'))
for i in range(0, sl_n):
    for j in range(0, ind_n):
        popu_slots[i, j, 0] = i*ind_n + j
print(popu_slots)

In [ ]:
ran_indic = 22
si = ran_indic // ind_n
ii = ran_indic % ind_n
indie = (si, ii)
x = popu_slots[indie]
x = x -100
print(popu_slots[indie])
print(x)

In [ ]:
t0 = time.time()
for i in range(0, 100):
    sl_ind = i % sl_n
    indi_ind = i % ind_n
    choose = popu_slots[sl_ind, indi_ind, :]
    choose = choose + 1
    # popu_slots[sl_ind, indi_ind, :] = choose
print(time.time() - t0)


In [ ]:
si = 3
ii = 2
# popu_slots[si].shape[0]
popu_slots[si, ii, 0]
print(popu_slots[-1])

In [ ]:
x = np.array(popu_slots[1][0]) + 1
print(x)
for s in popu_slots[-1]:
    print(np.abs(x - s).sum())
print(
    np.abs(x - popu_slots[-1]).sum()
)
50+51+52+53+54

In [ ]:
import matplotlib.pyplot as plt
reco = [444, 445, 445, 447, 449, 449, 449]
t    = [1000, 2000, 3000, 4000, 5000, 6000, 7000]
plt.plot(t, reco)
plt.show()

In [ ]:
sss = np.array([0, 1, 2, 3])
print(sss[1:3])

In [ ]:
np.where(sss == 0, 666, sss)



In [ ]:
slot = np.array([
    [0, 1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1],
    [0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0]
])
x= np.array(
    [0, 0, 1, 0, 0, 1])

# slot = slot.reshape(1, -1)
print(np.abs(x - slot))
print(
    np.sum(np.abs(x - slot), axis=1)
    )
print(
    np.min(np.sum(np.abs(x - slot), axis=1))
    )
diff = np.sum(np.abs(x - slot), axis=1)
# diff[2] = np.inf
print(diff)
print(np.max(diff))
diff[2] = np.max(diff)
print(diff)
print(np.min(diff))

In [ ]:
print(slot)
print(len(np.where(slot[:,1] == 3)[0]))
print(len(np.where(slot[:,1] == 0)[0]))
print(np.where(slot[:,2] == 1)[0])

In [ ]:
popu_slots[-1, 2, 1] = 4
popu_slots[-1, 3, 1] = 7
popu_slots[-1, 4, 1] = 5
print(popu_slots[-1])
print((np.where((popu_slots[-1, :, 0] > 47))[0]))
print((np.where((popu_slots[-1, :, 1] < 6))[0]))
print((np.where((popu_slots[-1, :, 0] > 47) & (popu_slots[-1, :, 1] < 6))[0]))

In [ ]:

fc = np.array([
    [9, 3],
    [2, 3],
    [3, 2],
    [5, 7],
    [5, 7],
    [5, 7],
    [5, 7],
    [5, 7],
    [4, 1]
])
# print(np.argmax(fc[0], axis=0))
# print(np.max(fc[:, 0], axis=0))
print((np.where((fc[ :, 1] < 6))[0]))

In [ ]:
sl = fc[:, 0]
sl += 999
fc

In [ ]:
f = fc[:, 0]
len(np.where(f == 5)[0])

In [ ]:
popu = np.zeros(5, 'int')
popu[2] = 1.0
popu[3] = 5.0
popu[4] = 3.0
popu

In [ ]:
f = np.array([1, 2, 3])
f_all = np.hstack((f, [[5]]))
print(f_all)

In [ ]:
np.arange(5)

In [ ]:
ind = [0, 1, 2, 3, 4, 5]
sli = fc[ind]
# print(sli)
# print(np.array(ind).reshape(-1, 1))
i_f_c = np.vstack((np.array(ind), [9, 6, 6, 6, 4, 3])).T
print(i_f_c)

In [ ]:
print(np.argsort(i_f_c[:, -1]))
print((i_f_c[:, -1]))

In [ ]:
i_f_c[[]]

In [ ]:
np.random.rand()

In [ ]:
ifc_sort = i_f_c[np.argsort(i_f_c[:, 1])]
print(ifc_sort)
wor = ifc_sort[-1, 1]
where = np.where(ifc_sort[:, 1] == 6)[0]
print(where)
w_pi = ifc_sort[where, 0]
print(w_pi)
w_ifc = i_f_c[w_pi]
print(w_ifc)

In [ ]:
i_f_c[:, :] = 0
print(i_f_c)
print(ind)

In [ ]:
fuck = np.all(fc == [4, 1], axis=1)
print(fuck)
print(np.any(
    fuck
))

In [ ]:
t = np.where((fc[ :, 1] < 6))[0]
list(t)

In [ ]:
ff = fc[1]
ff += 99
print(fc)

In [ ]:
sl_ham = np.array([
    [1],
    [8],
    [1],
    [2]
])
print(np.argmax(sl_ham))

In [ ]:
a = np.ones((1000,10000))

In [ ]:
for i in range(10_00):
    a[0, 0] = 999
    a = np.zeros(a.shape)
    # a = np.zeros_like(a)
    # a[:, :] = 0
print('!')
print(a.shape)

In [ ]:
k = [(1, 2), (9, 2), (4, 2)]
k.remove((9, 2))
print(k)

In [ ]:
L = 7.34566543
B = 8
n_sl = 10
wid = (2 * L)/10
print(wid)
cost_x = B
print(
    int(np.ceil((cost_x - (B - L)) / wid))
)


In [ ]:
def fuccc(li):
    li.append(-1)
lll = []
fuccc(lll)
print(lll)

In [ ]:
a = np.array([0,2,4,15,20,23,25,30,31,37,46,49,64,66,74,87,95,96,122,137,147,210,246,253,269])
b= np.array([0,2,4,15,20,23,25,30,31,37,46,49,64,66,74,77,87,96,122,137,140,210,246,337,414])
c= np.array([0,2,4,15,20,23,31,35,37,46,49,60,64,66,74,87,96,122,137,147,188,210,246,284,291])
d= np.array([0,2,4,15,20,23,25,31,35,37,46,49,64,66,74,87,95,96,122,137,147,165,210,246])
e= np.array([0,2,4,15,20,23,25,30,31,35,37,46,49,64,66,74,87,96,122,137,147,210,246,253,392])

In [ ]:
sl = [a, b, c, d, e]
for s in range(len(sl)):
    t = np.zeros(450)
    t[sl[s]] = 1
    sl[s] = t
# print(np.abs(sl[0] - sl[1]))
# print(np.abs(sl[0] - sl[1]).sum())
# print(sl)
for pi in sl:
    ham = 0
    for pj in sl:
        ham = np.abs(pi - pj).sum()
        print(ham)


In [ ]:
sl = np.array([[1, 0, 0, 1, 1, 0, 1], [1, 1, 1, 1, 1, 0, 1], [1, 0, 0, 1, 1, 0, 1]])
a = np.array([ 0, 0, 0, 0, 1, 1, 1])
print(a - sl)
print(np.sum(a - sl, axis=1))
print(np.sum(a - sl, axis=1).min())

In [28]:
import numpy as np

nn = 320_0000
p0 = 0.3
p1 = 0.7
s = np.zeros(nn, dtype='int')
s[nn // 2 : ] = 1
print('s           ', s)
print(s.sum())
print('--------------')
s_ori = np.copy(s)
change1_to_0 = np.random.binomial(1, p1, nn)
print('change1_to_0', change1_to_0)  # change位上1bit为要变，
print('change1_to_0', change1_to_0.sum())  # change位上1bit为要变，
# 让它仅对原1处起作用
change1_to_0 = np.multiply(s, change1_to_0)

change1_to_0 = 1 - change1_to_0
s = np.multiply(s, change1_to_0)

print('s           ',  s)
print('s1', s.sum())

change0_to_1 = np.random.binomial(1, p0, nn)
print('change0_to_1', change0_to_1)  # change位上1bit为要变，
print('change0_to_1', change0_to_1.sum())  # change位上1bit为要变，
# 让它仅对原0处起作用
change0_to_1 = np.multiply(1-s_ori, change0_to_1)
s += change0_to_1
print('s           ', s)
print(s.sum())

s            [0 0 0 ... 1 1 1]
1600000
--------------
change1_to_0 [0 1 1 ... 1 0 0]
change1_to_0 2240957
s            [0 0 0 ... 0 1 1]
s1 479323
change0_to_1 [0 1 0 ... 0 0 0]
change0_to_1 959216
s            [0 1 0 ... 0 1 1]
959188


In [121]:
i_f_c[:, :] = 0
print(i_f_c)
print(ind)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[0, 1, 2, 3, 4, 5]


In [19]:
fuck = np.all(fc == [4, 1], axis=1)
print(fuck)
print(np.any(
    fuck
))

[False False False False False False False False  True]
True


In [20]:
t = np.where((fc[ :, 1] < 6))[0]
list(t)

[0, 1, 2, 8]

In [21]:
ff = fc[1]
ff += 99
print(fc)

[[  9   3]
 [101 102]
 [  3   2]
 [  5   7]
 [  5   7]
 [  5   7]
 [  5   7]
 [  5   7]
 [  4   1]]


In [22]:
sl_ham = np.array([
    [1],
    [8],
    [1],
    [2]
])
print(np.argmax(sl_ham))

1


In [23]:
a = np.ones((1000,10000))

In [24]:
for i in range(10_00):
    a[0, 0] = 999
    a = np.zeros(a.shape)
    # a = np.zeros_like(a)
    # a[:, :] = 0
print('!')
print(a.shape)

!
(1000, 10000)


In [25]:
k = [(1, 2), (9, 2), (4, 2)]
k.remove((9, 2))
print(k)

[(1, 2), (4, 2)]


In [26]:
L = 7.34566543
B = 8
n_sl = 10
wid = (2 * L)/10
print(wid)
cost_x = B
print(
    int(np.ceil((cost_x - (B - L)) / wid))
)


1.469133086
5


In [27]:
def fuccc(li):
    li.append(-1)
lll = []
fuccc(lll)
print(lll)

[-1]


In [128]:
a = np.array([0,2,4,15,20,23,25,30,31,37,46,49,64,66,74,87,95,96,122,137,147,210,246,253,269])
b= np.array([0,2,4,15,20,23,25,30,31,37,46,49,64,66,74,77,87,96,122,137,140,210,246,337,414])
c= np.array([0,2,4,15,20,23,31,35,37,46,49,60,64,66,74,87,96,122,137,147,188,210,246,284,291])
d= np.array([0,2,4,15,20,23,25,31,35,37,46,49,64,66,74,87,95,96,122,137,147,165,210,246])
e= np.array([0,2,4,15,20,23,25,30,31,35,37,46,49,64,66,74,87,96,122,137,147,210,246,253,392])

In [140]:
sl = [a, b, c, d, e]
for s in range(len(sl)):
    t = np.zeros(450)
    t[sl[s]] = 1
    sl[s] = t
# print(np.abs(sl[0] - sl[1]))
# print(np.abs(sl[0] - sl[1]).sum())
# print(sl)
for pi in sl:
    ham = 0
    for pj in sl:
        ham = np.abs(pi - pj).sum()
        print(ham)


0.0
8.0
10.0
5.0
4.0
8.0
0.0
12.0
9.0
8.0
10.0
12.0
0.0
7.0
8.0
5.0
9.0
7.0
0.0
5.0
4.0
8.0
8.0
5.0
0.0


In [229]:
sl = np.array([[1, 0, 0, 1, 1, 0, 1], [1, 1, 1, 1, 1, 0, 1], [1, 0, 0, 1, 1, 0, 1]])
a = np.array([ 0, 0, 0, 0, 1, 1, 1])
print(a - sl)
print(np.sum(a - sl, axis=1))
print(np.sum(a - sl, axis=1).min())

[[-1  0  0 -1  0  1  0]
 [-1 -1 -1 -1  0  1  0]
 [-1  0  0 -1  0  1  0]]
[-1 -3 -1]
-3


In [23]:
import numpy as np

p0 = 0.3
p1 = 0.3
nn = 32_0000_00
s = np.zeros(nn, dtype='int')
s[nn // 2 : ] = 1
print('s           ', s)
print(s.sum())
print('--------------')
s_ori = np.copy(s)
change1_to_0 = np.random.binomial(1, p1, nn)
print('change1_to_0', change1_to_0)  # change位上1bit为要变，
print('change1_to_0', change1_to_0.sum())  # change位上1bit为要变，
# 让它仅对原1处起作用
change1_to_0 = np.multiply(s, change1_to_0)

change1_to_0 = 1 - change1_to_0
s = np.multiply(s, change1_to_0)

print('s           ',  s)
print('s1', s.sum())

change0_to_1 = np.random.binomial(1, p0, nn)
print('change0_to_1', change0_to_1)  # change位上1bit为要变，
print('change0_to_1', change0_to_1.sum())  # change位上1bit为要变，
# 让它仅对原0处起作用
change0_to_1 = np.multiply(1-s_ori, change0_to_1)

s += change0_to_1

print('s           ', s)
print(s.sum())

s            [0 0 0 ... 1 1 1]
16000000
--------------
change1_to_0 [0 0 1 ... 0 0 0]
change1_to_0 9597456
s            [0 0 0 ... 1 1 1]
s1 11201177
change0_to_1 [1 0 0 ... 0 1 1]
change0_to_1 9597279
s            [1 0 0 ... 1 1 1]
15996815


299417
